services:
  - type: worker
    name: attendance-6amb-bot
    env: python
    repo: https://github.com/tw-ngwan/attendancebot.git # optional
    region: singapore # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: main # optional (defaults to master)
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.2
      - key: TZ
        value: Asia/Singapore
      - key: DATABASE_URL
        fromDatabase: 
          name: attendance 
          property: connectionString

databases:
  - name: attendance
    user: attendance_7fq7_user 


envVarGroups:
  - name: conc-settings
    envVars:
      - key: TZ
        value: Asia/Singapore
      - key: DATABASE_URL
        fromDatabase: 
          name: attendance 
          property: connectionString
